version: "3.9"
services:
  api:
    build: .
    container_name: safehorizon_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app

  db:
    image: postgis/postgis:15-3.4
    container_name: safehorizon_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: safehorizon
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: safehorizon_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
