"""remove postgis columns and fix location schema

Revision ID: 3a974320dcc0
Revises: 3aeeb160372a
Create Date: 2025-09-28 23:14:02.091305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a974320dcc0'
down_revision = '3aeeb160372a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_locations_coords', table_name='locations')
    op.add_column('restricted_zones', sa.Column('radius_meters', sa.Float(), nullable=True))
    op.add_column('restricted_zones', sa.Column('bounds_json', sa.Text(), nullable=True))
    op.drop_index('idx_restricted_zones_center', table_name='restricted_zones')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_restricted_zones_center', 'restricted_zones', ['center_latitude', 'center_longitude'], unique=False)
    op.drop_column('restricted_zones', 'bounds_json')
    op.drop_column('restricted_zones', 'radius_meters')
    op.create_index('idx_locations_coords', 'locations', ['latitude', 'longitude'], unique=False)
    # ### end Alembic commands ###